### ISSUE TITLE
SpeakIt Missing from Chrome Store

### ISSUE THREAD

**Issue by itrtdorsey** [skechboy/SpeakIt#37]
SpeakIt is not in Chrome Store. What happened to it?

SpeakIt! - https://chrome.google.com/webstore/detail/announcify/mmiolkcfamcbpoandjpnefiegkcpeoan 
https://github.com/skechboy/SpeakIt

**Comment by Cgi-Chris** [comment]
There has been reports that the extension collects user information.

**Comment by itrtdorsey** [comment]
I heard that they were taken out for using collecting personal information.

That is a real shame. It was easy to use and worked well. I wonder if they will fix the "issue" and place it back in the Play Store?

**Comment by skechboy** [comment]
Marking this issue as duplicate with #39
